### ISSUE TITLE
example data 404

### ISSUE THREAD

**Issue by sailseem** [drug2ways/drug2ways#11]
Dear,
   I found out that all the example data links returned to 404, can you share this via another link? Thanks

![image](https://user-images.githubusercontent.com/72428172/133796935-79c982b5-7306-4c8d-bb22-14e97058ed25.png)

**Comment by ddomingof** [comment]
Sorry for the delay answer. The example data is present in this repo: 
https://github.com/drug2ways/results/tree/master/networks

**Comment by ddomingof** [comment]
I have updated now the links  @sailseem
