### ISSUE TITLE
Error reading example files

### ISSUE THREAD

**Issue by aalmodovares** [drug2ways/drug2ways#13]
When trying to execute the example with the custom network, I found an error in _graph_reader.py_ because the relation is defined as 'polarity' in the _constants.py_ script, while in the .tsv file it only finds the column 'relation'. I suppose I could avoid this error by changing the column name of the .tsv or modifying the _constants.py_ file. However, I find it strange that in none of the example networks is there a column named 'polarity' and I was wondering if there is something I am not taking into account.

**Comment by ddomingof** [comment]
Sorry you are right! The PR has been merged. Sorry that I have not replied. Somehow I didnt get a notification
