### ISSUE TITLE
Fix slow iteration during loading of network

### ISSUE THREAD

**Issue by cthoyt** [drug2ways/drug2ways#3]
If you use `df.values` you get potentially 100-1000x speed in loading.

https://github.com/drug2ways/drug2ways/blob/929269b1841ee561e4b35a643a0cd65ce70cf4e5/src/drug2ways/graph_reader.py#L196-L200

Alternatively, just use the super-fast method for loading from a pandas dataframe provided by networkx:

https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.convert_matrix.from_pandas_dataframe.html

**Comment by ddomingof** [comment]
The problem of using this method is that you need to have a specific column order and we would like to avoid that. The max time you will need is still slow (~1min for 1.000.000 edges)

**Comment by cthoyt** [comment]
That's not true - it picks the columns by names, and even allows the user to override the defaults

**Comment by ddomingof** [comment]
Okay! thanks! will fix it now
