### ISSUE TITLE
Give results in reasonable data structure

### ISSUE THREAD

**Issue by cthoyt** [drug2ways/drug2ways#6]
Right now, the following code is taking highly structured data and putting it into a string that needs to be parsed again later

https://github.com/drug2ways/drug2ways/blob/09b77c54bf97e70a885e62f0721ac72e9e8a09da/src/drug2ways/pathway.py#L95-L100

If there are two pieces of data that need to go together, either:

1. Don't use a dataframe as the datastructure to hold it. JSON is probably better.
2. make two columns

**Comment by ddomingof** [comment]
Closed with #adfbb01

**Comment by ddomingof** [comment]
Close with adfbb013a9046cb3ad89fd305a9647660fe39e42
