### ISSUE TITLE
Report name of pathway database that was being used for enrichment

### ISSUE THREAD

**Issue by cthoyt** [drug2ways/drug2ways#7]
The following code seems to use a hard-coded integer point to *some* pathway database, but it's not computationally possible to figure out what it is

https://github.com/drug2ways/drug2ways/blob/09b77c54bf97e70a885e62f0721ac72e9e8a09da/src/drug2ways/pathway.py#L111-L112

Idea on how to fix it:

The `genesets` object could be a dictionary from Identifiers.org prefix to the actual data, rather than a list that doesn't say what database it is at each position. This means updating `get_genesets`

https://github.com/drug2ways/drug2ways/blob/09b77c54bf97e70a885e62f0721ac72e9e8a09da/src/drug2ways/pathway.py#L147-L153

to return a dictionary, which seems pretty obvious, like this:

```python
def get_genesets() -> Mapping[str, ...]: 
     """Get gene sets as dicts.""" 
     return {
         'kegg.pathway': parse_gmt_file(KEGG_GENESETS), 
         'reactome': parse_gmt_file(REACTOME_GENESETS), 
         'wikipathways': parse_gmt_file(WIKIPATHWAYS_GENESETS), 
     }
```

Or even better, you switch over to external ComPath code that abstracts all of this away from the identities of the databases, so as new ones get added they get put in analysis automatically.

**Comment by ddomingof** [comment]
I dont want to rely on compath as it is not stable right now. I will change the  rest following your suggestions

**Comment by cthoyt** [comment]
I meant https://github.com/compath/compath-resources, since that's pretty independent of the BEL stuff

**Comment by cthoyt** [comment]
Oh... this branch is where that all becomes more obvious, but it's not done https://github.com/ComPath/compath-resources/pull/14/files
